# Generated by Django 5.0.1 on 2024-12-21 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=15)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Negocio.usuario')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cliente.direccion')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cliente.pago')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Producto',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle', models.IntegerField(null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Negocio.producto')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Repartidor.pedido')),
            ],
            options={
                'verbose_name': 'Detalle Producto',
                'verbose_name_plural': 'Detalle Productos',
                'db_table': 'Detalle Producto',
            },
        ),
    ]
